/*!
* Utilitarians - Tools for different languages and situations.
* This file version can be used as a Node.js module
*
* @description Tools for JavaScript
* @version		2.0.0
* @author		Gaël BLAISE
* @license		Mozilla Public License, version 2.0
!*/
function realTypeOf(b){try{return Object.prototype.toString.apply(b).substring(8,Object.prototype.toString.apply(b).indexOf("]"))}catch(a){$log.error(a);return"Undefined"}}function isDefined(b,a){a=("Boolean"===realTypeOf(a))?a:true;if(true===a){try{if("Object"===realTypeOf(b)){if(0===Object.keys(b).length){return false}}}catch(c){return false}}return !("String"===realTypeOf(b)&&""===b||"Null"===realTypeOf(b)||"Undefined"===realTypeOf(b))}function isInt(a){return parseFloat(a)===parseInt(a)&&!isNaN(parseInt(a))}function isFloat(a){return isDefined(parseFloat(a),false)&&!isNaN(parseFloat(a))}function typeVerification(b,a){if("String"===realTypeOf(a)){return a.toLowerCase()===realTypeOf(b).toLowerCase()}else{throw new TypeError("typeName must be a String !")
}}function LSDefined(){try{return typeof localStorage!=="undefined"}catch(a){}return false}function getItemFromLS(a){if("String"!==realTypeOf(a)&&"Array"!==realTypeOf(a)){throw new TypeError("name argument must be a string or an array of string")}else{if(realTypeOf(a)==="String"){return localStorage.getItem(a)}else{var c=[];for(var b=0;b<a.length;b++){if(realTypeOf(a[b])!=="String"){a[b]=a[b].toString()}c[b]=localStorage.getItem(a[b])}return c}}}function setItemToLS(b,d,a){if(realTypeOf(a)!=="Boolean"){throw new TypeError("iJSON argument must be a boolean indicating if the val param has to be stored as JSON")}else{if(realTypeOf(b)==="Array"&&realTypeOf(d)==="Array"&&d.length===b.length){for(var c=0;c<b.length;c++){if(null===d[c]){d[c]=""}else{if(realTypeOf(d[c])!=="String"){d[c]=d[c].toString()}}if(realTypeOf(b[c])!=="String"){b[c]=b[c].toString()}if(a===true){d[c]=JSON.stringify(d[c])}localStorage.setItem(b[c],d[c])}}else{if(realTypeOf(b)==="Array"&&realTypeOf(b[0])==="String"&&realTypeOf(d)==="String"){if(null===d){d=""
}if(a===true){d=JSON.stringify(d)}for(var c=0;c<b.length;c++){if(realTypeOf(b[c])!=="String"){b[c]=b[c].toString()}localStorage.setItem(b[c],d)}}else{if(realTypeOf(d)==="String"&&realTypeOf(b)==="String"){if(null===d){d=""}localStorage.setItem(b,d)}else{throw new Error()}}}}}function removeItemFromLS(a){if("String"!==realTypeOf(a)&&"Array"!==realTypeOf(a)){throw new TypeError("name argument must be a string or an array of string")}else{if(realTypeOf(a)==="Array"){for(var b=0;b<a.length;b++){if(realTypeOf(a[b])!=="String"){a[b]=a[b].toString()}localStorage.removeItem(a[b])}}else{localStorage.removeItem(a)}}}function getItemFromSS(a){if("String"!==realTypeOf(a)&&"Array"!==realTypeOf(a)){throw new TypeError("name argument must be a string or an array of string")}else{if(realTypeOf(a)==="Array"){var c=[];for(var b=0;b<a.length;b++){if(realTypeOf(a[b])!=="String"){a[b]=a[b].toString()}c[b]=sessionStorage.getItem(a[b])}return c}else{return sessionStorage.getItem(a)}}}function setItemToSS(b,d,a){if(realTypeOf(a)!=="Boolean"){throw new TypeError("isJson argument must be a boolean indicating if val argument is or not a JSON string")
}if(realTypeOf(b)==="Array"&&realTypeOf(d)==="Array"&&d.length===b.length){for(var c=0;c<b.length;c++){if(null===d[c]){d[c]=""}else{if(realTypeOf(d[c])!=="String"){d[c]=d[c].toString()}}if(realTypeOf(b[c])!=="String"){b[c]=b[c].toString()}if(a===true){d[c]=JSON.stringify(d[c])}sessionStorage.setItem(b[c],d[c])}}else{if(realTypeOf(b)==="Array"&&realTypeOf(d)==="String"){if(null===d){d=""}if(a===true){d=JSON.stringify(d)}for(var c=0;c<b.length;c++){if(realTypeOf(b[c])!=="String"){b[c]=b[c].toString()}sessionStorage.setItem(b[c],d)}}else{if(realTypeOf(d)==="String"&&realTypeOf(b)==="String"){if(null===d){d=""}sessionStorage.setItem(b,d)}else{throw new Error()}}}}function removeItemFromSS(a){if("String"!==realTypeOf(a)&&"Array"!==realTypeOf(a)){throw new TypeError("name argument must be a string or an array of string")}else{if(realTypeOf(a)==="Array"){for(var b=0;b<a.length;b++){if(realTypeOf(a[b])!=="String"){a[b]=a[b].toString()}sessionStorage.removeItem(a[b])}}else{sessionStorage.removeItem(a)
}}}function getFrDayName(a){if(!isInt(a)){throw new TypeError("The arguement must be an integer between 0 and 6")}switch(a){case 0:return"Dimanche";case 1:return"Lundi";case 2:return"Mardi";case 3:return"Mercredi";case 4:return"Jeudi";case 5:return"Vendredi";case 6:return"Samedi";default:throw new RangeError("The value must be in the specified range: [0-6]")}}function stringifyDateFr(a){if(null===a){a=new Date();return getFrDayName(a.getDay())+" "+(a.getDate()<10?"0"+a.getDate().toString():a.getDate().toString())+"-"+(a.getMonth()<10?"0"+a.getMonth().toString():a.getMonth().toString())+"-"+a.getFullYear().toString()+" "+(a.getHours()<10?"0"+a.getHours().toString():a.getHours().toString())+":"+(a.getMinutes()<10?"0"+a.getMinutes().toString():a.getMinutes().toString())+":"+(a.getSeconds()<10?"0"+a.getSeconds().toString():a.getSeconds().toString())+":"+(a.getMilliseconds()<10?"00"+a.getMilliseconds().toString():a.getMilliseconds()<100?"00"+a.getMilliseconds().toString():a.getMilliseconds().toString())
}else{if(realTypeOf(a)==="Date"){return getFrDayName(a.getDay())+" "+(a.getDate()<10?"0"+a.getDate().toString():a.getDate().toString())+"-"+(a.getMonth()<10?"0"+a.getMonth().toString():a.getMonth().toString())+"-"+a.getFullYear().toString()+" "+(a.getHours()<10?"0"+a.getHours().toString():a.getHours().toString())+":"+(a.getMinutes()<10?"0"+a.getMinutes().toString():a.getMinutes().toString())+":"+(a.getSeconds()<10?"0"+a.getSeconds().toString():a.getSeconds().toString())+":"+(a.getMilliseconds()<10?"00"+a.getMilliseconds().toString():a.getMilliseconds()<100?"00"+a.getMilliseconds().toString():a.getMilliseconds().toString())}else{throw new TypeError("The argument must be a Date, or set to null")}}}function isIE9Plus(){var a=navigator.userAgent.toLowerCase();return -1===a.indexOf("msie")?true:8<=parseInt(a.split("msie")[1])}function hasSpecifiedNodeParent(a,c){var b=a;if(!isDefined(c)){return false}else{if("String"!==realTypeOf(c)){throw new TypeError("parentNodeName argument must be a non-empty string !")
}else{if(b.parentNode.nodeName.toLowerCase()===c){return true}else{do{if(c.toLowerCase()!==b.nodeName.toLowerCase()){b=b.parentNode}}while(null!==b&&b.nodeName.toLowerCase()!==c)}}}return null!==b}function defineConstantForObject(c,b,f,a,d){if("String"===realTypeOf(b)){Object.defineProperty(c,b,{value:f,writable:false,enumerable:("Boolean"===realTypeOf(a))?a:true,configurable:("Boolean"===realTypeOf(d))?d:false})}else{throw new TypeError("constName must be an String !")}}function ipV4Validation(c){if("localhost"!==c){var a;if("String"===utils.realTypeOf(c)){a=c.split(".")}else{return false}if(4!==a.length){return false}for(var b=0;b<a.length;b++){if(0>parseInt(a[b])||255<parseInt(a[b])||isNaN(parseInt(a[b]))||false===isDefined(a[b])){return false}}return true}else{return true}}function portValidation(a){if(isNaN(parseInt(a))||parseInt(a)!==parseFloat(a)){return false}else{if(0>parseInt(a)||65535<=parseInt(a)){return false}}return true}var utils={realTypeOf:realTypeOf,isDefined:isDefined,isInt:isInt,isFloat:isFloat,typeVerification:typeVerification,LSDefined:LSDefined,getItemFromLS:getItemFromLS,setItemToLS:setItemToLS,removeItemFromLS:removeItemFromLS,getItemFromSS:getItemFromSS,setItemToSS:setItemToSS,removeItemFromSS:removeItemFromSS,getFrDayName:getFrDayName,stringifyDateFr:stringifyDateFr,isIE9Plus:isIE9Plus,hasSpecifiedNodeParent:hasSpecifiedNodeParent,defineConstantForObject:defineConstantForObject,ipV4Validation:ipV4Validation,portValidation:portValidation};
defineConstantForObject(utils,"version","2.0.0",true,false);defineConstantForObject(utils,"minified",false,true,false);try{module.exports=utils}catch(e){};