/*!
 * Utilitarians - Tools for different languages and situations.
 * This version can be used as a Node.js module
 *
 * @description Tools for JavaScript
 * @version     1.3.0
 * @author      Gaël BLAISE
 * @license     Mozilla Public License, version 2.0
!*/
;function realTypeOf(b){try{return Object.prototype.toString.apply(b).substring(8,Object.prototype.toString.apply(b).indexOf("]"))}catch(a){console.error(a);return"Undefined"}}function isDefined(b,a){a=("Boolean"===realTypeOf(a))?a:true;if(true===a){try{if("Object"===realTypeOf(b)){if(0===Object.keys(b).length){return false}}}catch(c){return false}}return !("String"===realTypeOf(b)&&""===b||"Null"===realTypeOf(b)||"Undefined"===realTypeOf(b))}function isInt(a){return parseFloat(a)===parseInt(a)&&!isNaN(parseInt(a))}function isFloat(a){return isDefined(parseFloat(a))&&!isNaN(parseFloat(a))}function typeVerificator(b,a){if("String"===realTypeOf(a)){return a.toLowerCase()===realTypeOf(b).toLowerCase()}else{throw new TypeError("typeName must be a String !")
}}function LSDefinied(){var a;try{a=typeof localStorage!=="undefined"}catch(b){a=false}return a}function getItemFromLS(b){var d=[],a=realTypeOf(b)==="String";if(realTypeOf(b)==="Array"){for(var c=0;c<b.length;c++){if(realTypeOf(b[c])!=="String"){b[c]=b[c].toString()}d[c]=localStorage.getItem(b[c])}}else{if(a===true){d[0]=localStorage.getItem(b)}}if(d.length===1){return d[0]}else{return d}}function setItemToLS(b,d,a){if(realTypeOf(a)==="Boolean"){if(realTypeOf(b)==="Array"&&realTypeOf(d)==="Array"&&d.length===b.length){for(var c=0;c<b.length;c++){if(null===d[c]){d[c]=""}else{if(realTypeOf(d[c])!=="String"){d[c]=d[c].toString()}}if(realTypeOf(b[c])!=="String"){b[c]=b[c].toString()}if(a===true){d[c]=JSON.stringify(d[c])}localStorage.setItem(b[c],d[c])}}else{if(realTypeOf(b)==="Array"&&realTypeOf(b[0])==="String"&&realTypeOf(d)==="String"){if(null===d){d=""}if(a===true){d=JSON.stringify(d)}for(var c=0;c<b.length;c++){if(realTypeOf(b[c])!=="String"){b[c]=b[c].toString()}localStorage.setItem(b[c],d)
}}else{if(realTypeOf(d)==="String"&&realTypeOf(b)==="String"){if(null===d){d=""}localStorage.setItem(b,d)}else{throw new Error()}}}}else{throw new TypeError("iJSON argument must be a boolean indicating if val is or not a JSON String")}}function removeItemFromLS(b){var a=realTypeOf(b)==="String";if(realTypeOf(b)==="Array"){for(var c=0;c<b.length;c++){if(realTypeOf(b[c])!=="String"){b[c]=b[c].toString()}localStorage.removeItem(b[c])}}else{if(a===true){localStorage.removeItem(b)}else{throw new TypeError("name argument must be a string or an array of string")}}}function getItemFromSS(b){var d=[],a=realTypeOf(b)==="String";if(realTypeOf(b)==="Array"){for(var c=0;c<b.length;c++){if(realTypeOf(b[c])==="String"){a=true}}for(var c=0;c<b.length;c++){d[c]=sessionStorage.getItem(b[c])}}else{if(a===true){d[0]=sessionStorage.getItem(b)}else{console.log("Le type envoyé pour le paramètre d'entrée n'est pas correct !");return}}if(d.length===1){return d[0]}else{return d}}function setItemToSS(b,d,a){if(realTypeOf(a)==="Boolean"){if(realTypeOf(b)==="Array"&&realTypeOf(d)==="Array"&&d.length===b.length){for(var c=0;
c<b.length;c++){if(null===d[c]){d[c]=""}else{if(realTypeOf(d[c])!=="String"){d[c]=d[c].toString()}}if(realTypeOf(b[c])!=="String"){b[c]=b[c].toString()}if(a===true){d[c]=JSON.stringify(d[c])}sessionStorage.setItem(b[c],d[c])}}else{if(realTypeOf(b)==="Array"&&realTypeOf(b[0])==="String"&&realTypeOf(d)==="String"){if(null===d){d=""}if(a===true){d=JSON.stringify(d)}for(var c=0;c<b.length;c++){if(realTypeOf(b[c])!=="String"){b[c]=b[c].toString()}sessionStorage.setItem(b[c],d)}}else{if(realTypeOf(d)==="String"&&realTypeOf(b)==="String"){if(null===d){d=""}sessionStorage.setItem(b,d)}else{throw new Error()}}}}else{throw new TypeError("isJson argument must be a boolean indicating if val argument is or not a JSON string")}}function removeItemFromSS(b){var a=realTypeOf(b)==="String";if(realTypeOf(b)==="Array"){for(var c=0;c<b.length;c++){if(realTypeOf(b[c])!=="String"){b[c]=b[c].toString()}sessionStorage.removeItem(b[c])}}else{if(a===true){sessionStorage.removeItem(b)}else{throw new TypeError("name argument must be a string, or an array of string !")
}}}function getFrDayName(a){if(!isInt(a)){throw new TypeError("The arguement must be an integer between 1 and 7")}switch(a){case 1:return"Lundi";case 2:return"Mardi";case 3:return"Mercredi";case 4:return"Jeudi";case 5:return"Vendredi";case 6:return"Samedi";case 7:return"Dimanche";default:throw new RangeError("The value must be in the specified range: [1-7]")}}function stringifyDateFr(a){if(null===a){a=new Date();return getFrDayName(a.getDay())+" "+(a.getDate()<10?"0"+a.getDate().toString():a.getDate().toString())+"-"+(a.getMonth()<10?"0"+a.getMonth().toString():a.getMonth().toString())+"-"+a.getFullYear().toString()+" "+(a.getHours()<10?"0"+a.getHours().toString():a.getHours().toString())+":"+(a.getMinutes()<10?"0"+a.getMinutes().toString():a.getMinutes().toString())+":"+(a.getSeconds()<10?"0"+a.getSeconds().toString():a.getSeconds().toString())+":"+(a.getMilliseconds()<10?"00"+a.getMilliseconds().toString():a.getMilliseconds()<100?"00"+a.getMilliseconds().toString():a.getMilliseconds().toString())
}else{if(realTypeOf(a)==="Date"){return getFrDayName(a.getDay())+" "+(a.getDate()<10?"0"+a.getDate().toString():a.getDate().toString())+"-"+(a.getMonth()<10?"0"+a.getMonth().toString():a.getMonth().toString())+"-"+a.getFullYear().toString()+" "+(a.getHours()<10?"0"+a.getHours().toString():a.getHours().toString())+":"+(a.getMinutes()<10?"0"+a.getMinutes().toString():a.getMinutes().toString())+":"+(a.getSeconds()<10?"0"+a.getSeconds().toString():a.getSeconds().toString())+":"+(a.getMilliseconds()<10?"00"+a.getMilliseconds().toString():a.getMilliseconds()<100?"00"+a.getMilliseconds().toString():a.getMilliseconds().toString())}else{throw new TypeError("The argument must be a Date, or set to null")}}}function visitRecursively(c){var b=c.children;execute(c);for(var a=0;a<b.length;a++){visitRecursively(b[a])}}function execute(a){}function isIE9Plus(){var a=navigator.userAgent.toLowerCase();return -1===a.indexOf("msie")?true:8>parseInt(a.split("msie")[1])?false:true}function hasSpecifiedNodeParent(a,c){var b;
if(!isDefined(c)){return false}if("String"!==realTypeOf(c)){throw new TypeError("parentNodeName argument must be a non-empty string !")}do{if(c.toLowerCase()!==b.nodeName.toLowerCase()){b=b.parentNode}}while(null!==b&&b.nodeName.toLowerCase()!==c);return null!==b}function defineConstantForObject(c,b,f,a,d){if("String"===realTypeOf(b)){Object.defineProperty(c,b,{value:f,writable:false,enumerable:("Boolean"===realTypeOf(a))?a:true,configurable:("Boolean"===realTypeOf(d))?d:true})}else{throw new TypeError("constName must be an String !")}}function ipValidation(c){if("localhost"!==c){var a;if("String"===utils.realTypeOf(c)){a=c.split(".")}else{return false}if(4!==a.length){return false}for(var b=0;b<a.length;b++){if(0>parseInt(a[b])||255<parseInt(a[b])||isNaN(parseInt(a[b]))||false===isDefined(a[b])){return false}}return true}}function portValidation(a){if(isNaN(parseInt(a))||parseInt(a)!==parseFloat(a)){return false}else{if(0>parseInt(a)||65535<=parseInt(a)){return false}}return true}var utils={realTypeOf:realTypeOf,isDefined:isDefined,isInt:isInt,isFloat:isFloat,typeVerificator:typeVerificator,LSDefinied:LSDefinied,getItemFromLS:getItemFromLS,setItemToLS:setItemToLS,removeItemFromLS:removeItemFromLS,getItemFromSS:getItemFromSS,setItemToSS:setItemToSS,removeItemFromSS:removeItemFromSS,getFrDayName:getFrDayName,stringifyDateFr:stringifyDateFr,isIE9Plus:isIE9Plus,hasSpecifiedNodeParent:hasSpecifiedNodeParent,defineConstantForObject:defineConstantForObject,ipValidation:ipValidation,portValidation:portValidation};
defineConstantForObject(utils,"version","1.3.0");defineConstantForObject(utils,"minify",true);try{module.exports=utils}catch(e){};